### Label Encoder

In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from sklearn.datasets import load_iris

In [2]:
data =load_iris(as_frame=True).frame
data

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [3]:
data.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [4]:
#Changes does not effect the "data" dataframe
data1=data.copy()

In [5]:
labelencoder = LabelEncoder()
data1.iloc[:, -1] = labelencoder.fit_transform(data1.iloc[:,-1])

In [6]:
data1

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

### One Hot Encoder

#### Using sklearn

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
import pandas as pd

# from google.colab import files
# uploaded = files.upload()

data2 = pd.read_csv("iris.csv")
data2.head()

FileNotFoundError: [Errno 2] No such file or directory: 'iris.csv'

In [ ]:
data2

In [9]:
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')

In [14]:
enc_df = pd.DataFrame(enc.fit_transform(data2[['species']]).toarray())
enc_df

       0    1    2
0    1.0  0.0  0.0
1    1.0  0.0  0.0
2    1.0  0.0  0.0
3    1.0  0.0  0.0
4    1.0  0.0  0.0
..   ...  ...  ...
145  0.0  0.0  1.0
146  0.0  0.0  1.0
147  0.0  0.0  1.0
148  0.0  0.0  1.0
149  0.0  0.0  1.0

[150 rows x 3 columns]

In [16]:
# merge with main df 
data_final = data2.iloc[:,0:4].join(enc_df)
data_final

     sepal_length  sepal_width  petal_length  petal_width    0    1    2
0             5.1          3.5           1.4          0.2  1.0  0.0  0.0
1             4.9          3.0           1.4          0.2  1.0  0.0  0.0
2             4.7          3.2           1.3          0.2  1.0  0.0  0.0
3             4.6          3.1           1.5          0.2  1.0  0.0  0.0
4             5.0          3.6           1.4          0.2  1.0  0.0  0.0
..            ...          ...           ...          ...  ...  ...  ...
145           6.7          3.0           5.2          2.3  0.0  0.0  1.0
146           6.3          2.5           5.0          1.9  0.0  0.0  1.0
147           6.5          3.0           5.2          2.0  0.0  0.0  1.0
148           6.2          3.4           5.4          2.3  0.0  0.0  1.0
149           5.9          3.0           5.1          1.8  0.0  0.0  1.0

[150 rows x 7 columns]

#### Using Pandas

In [18]:
import pandas as pd

from google.colab import files
uploaded = files.upload()

data3 = pd.read_csv("iris.csv")
data3.head()

Saving iris.csv to iris (1).csv

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [19]:
data_encoded=pd.get_dummies(data3)

In [20]:
data_encoded

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1

#### IsolationForest

In [21]:
from sklearn.ensemble import IsolationForest

In [22]:
data_encoded

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1

In [23]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

IsolationForest(contamination=0.01, random_state=10)

In [24]:
# predictions
y_pred_outliers = clf.predict(data_encoded)

In [26]:
#-1 for outliers and 1 for inliers.
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [27]:
## Let us add a new data point which is outlier
data_encoded.loc[150]=[20,40,30,50,1,0,0]

In [28]:
data_encoded

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1
150,20.0,40.0,30.0,50.0,1,0,0

In [35]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)
# predictions
y_pred_outliers = clf.predict(data_encoded)
y_pred_outliers

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1])

In [36]:
data_encoded['scores']=clf.decision_function(data_encoded)
data_encoded

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica,scores
0,5.1,3.5,1.4,0.2,1,0,0,0.210048
1,4.9,3.0,1.4,0.2,1,0,0,0.168467
2,4.7,3.2,1.3,0.2,1,0,0,0.184877
3,4.6,3.1,1.5,0.2,1,0,0,0.178048
4,5.0,3.6,1.4,0.2,1,0,0,0.198004
...,...,...,...,...,...,...,...,...
146,6.3,2.5,5.0,1.9,0,0,1,0.169546
147,6.5,3.0,5.2,2.0,0,0,1,0.195624
148,6.2,3.4,5.4,2.3,0,0,1,0.147483
149,5.9,3.0,5.1,1.8,0,0,1,0.160186
150,20.0,40.0,30.0,50.0,1,0,0,-0.275522

In [38]:
data_encoded['anomaly']=clf.predict(data_encoded.iloc[:,0:8])

In [39]:
data_encoded

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica,scores,anomaly
0,5.1,3.5,1.4,0.2,1,0,0,0.210048,1
1,4.9,3.0,1.4,0.2,1,0,0,0.168467,1
2,4.7,3.2,1.3,0.2,1,0,0,0.184877,1
3,4.6,3.1,1.5,0.2,1,0,0,0.178048,1
4,5.0,3.6,1.4,0.2,1,0,0,0.198004,1
...,...,...,...,...,...,...,...,...,...
146,6.3,2.5,5.0,1.9,0,0,1,0.169546,1
147,6.5,3.0,5.2,2.0,0,0,1,0.195624,1
148,6.2,3.4,5.4,2.3,0,0,1,0.147483,1
149,5.9,3.0,5.1,1.8,0,0,1,0.160186,1
150,20.0,40.0,30.0,50.0,1,0,0,-0.275522,-1

In [40]:
#Print the outlier data points
data_encoded[data_encoded['anomaly']==-1]

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica,scores,anomaly
118,7.7,2.6,6.9,2.3,0,0,1,-0.002353,-1
150,20.0,40.0,30.0,50.0,1,0,0,-0.275522,-1

### PPS score

In [41]:
#install the package
!pip install ppscore

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting ppscore
  Downloading ppscore-1.3.0.tar.gz (17 kB)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from ppscore) (1.3.5)
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in /usr/local/lib/python3.8/dist-packages (from ppscore) (1.0.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2022.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas<2.0.0,>=1.0.0->ppscore) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (3.1.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.7.3)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.2.0)
Building wheels for collected packages: ppscore
  Building wheel for ppscore (setup.py) ... done
  Created wheel for ppscore: filename=ppscore-1.3.0-py2.py3-none-any.whl size=13166 sha256=571b77041787df0b08b4d2a72cb8552a9afcee1a8e26e2d53542dff535e59f6d
  Stored in directory: /root/.cache/pip/wheels/5c/80/75/b631985b161d4a29cc0cf94b5f64b00be6297b0968ff1337ce
Successfully built ppscore
Installing collected packages: ppscore
Successfully installed ppscore-1.3.0

In [42]:
import ppscore as pps

In [43]:
data.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [45]:
#pps.score(df, "feature_column", "target_column")  syntax
pps.score(data, "sepal length (cm)", "petal length (cm)")

{'x': 'sepal length (cm)',
 'y': 'petal length (cm)',
 'ppscore': 0.550422595049248,
 'case': 'regression',
 'is_valid_score': True,
 'metric': 'mean absolute error',
 'baseline_score': 1.4886666666666668,
 'model_score': 0.6692708968366863,
 'model': DecisionTreeRegressor()}

In [46]:
#calculate the whole PPS matrix
pps.matrix(data)

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,sepal length (cm),sepal length (cm),1.000000,predict_itself,True,None,0.000000,1.000000,None
1,sepal length (cm),sepal width (cm),0.000000,regression,True,mean absolute error,0.330667,0.364704,DecisionTreeRegressor()
2,sepal length (cm),petal length (cm),0.550423,regression,True,mean absolute error,1.488667,0.669271,DecisionTreeRegressor()
3,sepal length (cm),petal width (cm),0.431739,regression,True,mean absolute error,0.644667,0.366339,DecisionTreeRegressor()
4,sepal length (cm),target,0.346619,regression,True,mean absolute error,0.666667,0.435587,DecisionTreeRegressor()
5,sepal width (cm),sepal length (cm),0.006966,regression,True,mean absolute error,0.684667,0.679897,DecisionTreeRegressor()
6,sepal width (cm),sepal width (cm),1.000000,predict_itself,True,None,0.000000,1.000000,None
7,sepal width (cm),petal length (cm),0.172375,regression,True,mean absolute error,1.488667,1.232058,DecisionTreeRegressor()
8,sepal width (cm),petal width (cm),0.132858,regression,True,mean absolute error,0.644667,0.559017,DecisionTreeRegressor()
9,sepal width (cm),target,0.074871,regression,True,mean absolute error,0.666667,0.616753,DecisionTreeRegressor()
10,petal length (cm),sepal length (cm),0.525617,regression,True,mean absolute error,0.684667,0.324794,DecisionTreeRegressor()
11,petal length (cm),sepal width (cm),0.052136,regression,True,mean absolute error,0.330667,0.313427,DecisionTreeRegressor()
12,petal length (cm),petal length (cm),1.000000,predict_itself,True,None,0.000000,1.000000,None
13,petal length (cm),petal width (cm),0.744945,regression,True,mean absolute error,0.644667,0.164425,DecisionTreeRegressor()
14,petal length (cm),target,0.881789,regression,True,mean absolute error,0.666667,0.078808,DecisionTreeRegressor()
15,petal width (cm),sepal length (cm),0.383911,regression,True,mean absolute error,0.684667,0.421816,DecisionTreeRegressor()
16,petal width (cm),sepal width (cm),0.254616,regression,True,mean absolute error,0.330667,0.246474,DecisionTreeRegressor()
17,petal width (cm),petal length (cm),0.798274,regression,True,mean absolute error,1.488667,0.300302,DecisionTreeRegressor()
18,petal width (cm),petal width (cm),1.000000,predict_itself,True,None,0.000000,1.000000,None
19,petal width (cm),target,0.880127,regression,True,mean absolute error,0.666667,0.079915,DecisionTreeRegressor()
20,target,sepal length (cm),0.409634,regression,True,mean absolute error,0.684667,0.404204,DecisionTreeRegressor()
21,target,sepal width (cm),0.194307,regression,True,mean absolute error,0.330667,0.266416,DecisionTreeRegressor()
22,target,petal length (cm),0.785393,regression,True,mean absolute error,1.488667,0.319479,DecisionTreeRegressor()
23,target,petal width (cm),0.755749,regression,True,mean absolute error,0.644667,0.157460,DecisionTreeRegressor()
24,target,target,1.000000,predict_itself,True,None,0.000000,1.000000,None